# Generated by Django 6.0.6 on 2026-06-27 01:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('idcolor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'SH_Color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('idcupon', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uso_maximo', models.PositiveIntegerField()),
                ('uso_por_usuario', models.PositiveIntegerField()),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('valido_desde', models.DateTimeField()),
                ('valido_hasta', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Cupon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('iddescuento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valido_desde', models.DateTimeField()),
                ('valido_hasta', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Descuento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('iddireccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_destinatario', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('residencia', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=15)),
                ('principal', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Direccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idgenero', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Genero',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('idimpuesto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Impuesto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('idmarca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Marca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NunDocumento',
            fields=[
                ('idnumero', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigla', models.CharField(blank=True, max_length=5, null=True)),
                ('nombre', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Tipo_Documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idperfil', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('idtalla', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'SH_Talla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.genero')),
            ],
            options={
                'db_table': 'SH_Categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('idarticulo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=220, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('impuestos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.impuestos')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marcas')),
            ],
            options={
                'db_table': 'SH_Articulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idorden', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_impuestos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cupones')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.direcciones')),
            ],
            options={
                'db_table': 'SH_Orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemsOrden',
            fields=[
                ('iditmorden', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.descuentos')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden')),
            ],
            options={
                'db_table': 'SH_Items_Compra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('identrega', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transportadora', models.CharField(max_length=100)),
                ('numero_guia', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=30)),
                ('fecha_estimada', models.DateTimeField()),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden')),
            ],
            options={
                'db_table': 'SH_Entrega',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('idpago', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=30)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden')),
            ],
            options={
                'db_table': 'SH_Pagos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idfactura', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=30, unique=True)),
                ('base_gravable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(max_length=20)),
                ('numero_resolucion_dian', models.CharField(max_length=50)),
                ('prefijo_factura', models.CharField(max_length=10)),
                ('cufe', models.CharField(max_length=200)),
                ('qr_url', models.CharField(max_length=500)),
                ('ambiente', models.CharField(max_length=15)),
                ('emitida_en', models.DateTimeField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pagos')),
            ],
            options={
                'db_table': 'SH_Factura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.perfil')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nundocumento')),
            ],
            options={
                'db_table': 'SH_Usuarios',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('idnotificacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'SH_Notificacion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='direcciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('iddevolucion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(max_length=20)),
                ('monto_reembolso', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_reembolso', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('item_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemsorden')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'SH_Devolucion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'SH_Carrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VariantesArticulos',
            fields=[
                ('idvararticulo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('stock', models.IntegerField()),
                ('precio_extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.CharField(max_length=1000)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articulos')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colores')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tallas')),
            ],
            options={
                'db_table': 'SH_Variante_Articulos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('idmovinventario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
                ('cantidad', models.PositiveIntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_resultante', models.IntegerField()),
                ('motivo', models.CharField(max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variantesarticulos')),
            ],
            options={
                'db_table': 'SH_Movimiento_Inventario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='itemsorden',
            name='vararticulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.variantesarticulos'),
        ),
        migrations.CreateModel(
            name='ItemsCarrito',
            fields=[
                ('iditmcarrito', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrito')),
                ('vararticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variantesarticulos')),
            ],
            options={
                'db_table': 'SH_Items_Carrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArticuloDescuento',
            fields=[
                ('idartdescuento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.descuentos')),
                ('vararticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variantesarticulos')),
            ],
            options={
                'db_table': 'SH_Articulo_Descuento',
                'managed': True,
            },
        ),
    ]
