# Generated by Django 6.0.6 on 2026-09-08 01:37

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Reglas_Tallaje',
            fields=[
                ('idregla', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Cat_Reglas_Tallaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('idcolor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'SH_Color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('idcupon', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uso_maximo', models.PositiveIntegerField()),
                ('uso_por_usuario', models.PositiveIntegerField()),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('valido_desde', models.DateTimeField()),
                ('valido_hasta', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Cupon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('iddescuento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valido_desde', models.DateTimeField()),
                ('valido_hasta', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Descuento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idgenero', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Genero',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('idimpuesto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Impuesto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('idmarca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Marca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NunDocumento',
            fields=[
                ('idnumero', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigla', models.CharField(blank=True, max_length=5, null=True)),
                ('nombre', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Tipo_Documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idperfil', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idusuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.nundocumento')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.perfil')),
            ],
            options={
                'db_table': 'SH_Usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SH_Carrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.genero')),
            ],
            options={
                'db_table': 'SH_Categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('iddireccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_destinatario', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('residencia', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=15)),
                ('principal', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SH_Direccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('idnotificacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SH_Notificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idorden', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_impuestos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cupones')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.direcciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SH_Orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemsOrden',
            fields=[
                ('iditmorden', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.descuentos')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden')),
            ],
            options={
                'db_table': 'SH_Items_Compra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('identrega', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transportadora', models.CharField(max_length=100)),
                ('numero_guia', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=30)),
                ('fecha_estimada', models.DateTimeField()),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden')),
            ],
            options={
                'db_table': 'SH_Entrega',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('iddevolucion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(max_length=20)),
                ('monto_reembolso', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_reembolso', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemsorden')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden')),
            ],
            options={
                'db_table': 'SH_Devolucion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('idpago', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=30)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden')),
            ],
            options={
                'db_table': 'SH_Pagos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idfactura', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=30, unique=True)),
                ('base_gravable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(max_length=20)),
                ('numero_resolucion_dian', models.CharField(max_length=50)),
                ('prefijo_factura', models.CharField(max_length=10)),
                ('cufe', models.CharField(max_length=200)),
                ('qr_url', models.CharField(max_length=500)),
                ('ambiente', models.CharField(max_length=15)),
                ('emitida_en', models.DateTimeField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pagos')),
            ],
            options={
                'db_table': 'SH_Factura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prendas',
            fields=[
                ('idprenda', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=120, null=True)),
                ('regla_tallaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prendas', to='core.cat_reglas_tallaje')),
            ],
            options={
                'db_table': 'SH_Prendas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('idarticulo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=220, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('impuestos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.impuestos')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marcas')),
                ('prendas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prendas')),
            ],
            options={
                'db_table': 'SH_Articulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('idtalla', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('regla_tallaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='core.cat_reglas_tallaje')),
            ],
            options={
                'db_table': 'SH_Talla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VariantesArticulos',
            fields=[
                ('idvararticulo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('stock', models.IntegerField()),
                ('precio_extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=core.models.Ruta_foto_articulo)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articulos')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colores')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tallas')),
            ],
            options={
                'db_table': 'SH_Variante_Articulos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('idmovinventario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
                ('cantidad', models.PositiveIntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_resultante', models.IntegerField()),
                ('motivo', models.CharField(max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variantesarticulos')),
            ],
            options={
                'db_table': 'SH_Movimiento_Inventario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='itemsorden',
            name='vararticulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.variantesarticulos'),
        ),
        migrations.CreateModel(
            name='ItemsCarrito',
            fields=[
                ('iditmcarrito', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrito')),
                ('vararticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variantesarticulos')),
            ],
            options={
                'db_table': 'SH_Items_Carrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FotoVarianteArticulo',
            fields=[
                ('idfoto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.ImageField(upload_to=core.models.Ruta_foto_articulo)),
                ('variante_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variantesarticulos')),
            ],
            options={
                'db_table': 'SH_Foto_articulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArticuloDescuento',
            fields=[
                ('idartdescuento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_inicial', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_restante', models.CharField(blank=True, max_length=100, null=True)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.descuentos')),
                ('vararticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variantesarticulos')),
            ],
            options={
                'db_table': 'SH_Articulo_Descuento',
                'managed': True,
            },
        ),
    ]
