# Generated by Django 6.0.6 on 2026-06-28 17:29

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Perfil',
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(default=core.models.get_perfil_cliente, on_delete=django.db.models.deletion.PROTECT, to='core.perfil'),
        ),
    ]
