# Generated by Django 6.0.6 on 2026-07-13 23:09

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_perfil_usuario_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoVarianteArticulo',
            fields=[
                ('idfoto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.ImageField(upload_to=core.models.Ruta_foto_articulo)),
                ('variante_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variantesarticulos')),
            ],
            options={
                'db_table': 'SH_Foto_articulo',
                'managed': True,
            },
        ),
    ]
