# Generated by Django 6.0.6 on 2026-07-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fotovariantearticulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantesarticulos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img_variantes'),
        ),
    ]
