# Generated by Django 6.0.6 on 2026-07-25 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_variantesarticulos_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposPrendas',
            fields=[
                ('idprenda', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'SH_Tipo_prendas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='articulos',
            name='prendas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tiposprendas'),
        ),
    ]
