# Generated by Django 6.0.6 on 2026-07-26 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tiposprendas_articulos_prendas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallasPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tiposprendas')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tallas')),
            ],
            options={
                'db_table': 'SH_Tallas_Prendas',
            },
        ),
        migrations.AddField(
            model_name='tiposprendas',
            name='tallas',
            field=models.ManyToManyField(through='core.TallasPrendas', to='core.tallas'),
        ),
        migrations.AddConstraint(
            model_name='tallasprendas',
            constraint=models.UniqueConstraint(fields=('prenda', 'talla'), name='uq_prenda_talla'),
        ),
    ]
