# Generated by Django 6.0.6 on 2026-07-26 01:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tallasprendas_tiposprendas_tallas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Reglas_Tallaje',
            fields=[
                ('idregla', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SH_Cat_Reglas_Tallaje',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='TiposPrendas',
            new_name='Prendas',
        ),
        migrations.RemoveField(
            model_name='prendas',
            name='tallas',
        ),
        migrations.AlterModelTable(
            name='prendas',
            table='SH_Prendas',
        ),
        migrations.RemoveConstraint(
            model_name='tallasprendas',
            name='uq_prenda_talla',
        ),
        migrations.AddField(
            model_name='tallas',
            name='regla_tallaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='core.cat_reglas_tallaje'),
        ),
        migrations.AddField(
            model_name='prendas',
            name='regla_tallaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prendas', to='core.cat_reglas_tallaje'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='prendas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prendas'),
        ),
        migrations.RemoveField(
            model_name='tallasprendas',
            name='prenda',
        ),
        migrations.RemoveField(
            model_name='tallasprendas',
            name='talla',
        ),
        migrations.DeleteModel(
            name='TallasPrendas',
        ),
    ]
