# Generated by Django 6.0.6 on 2026-07-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cat_reglas_tallaje_prendas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulodescuento',
            name='cantidad_inicial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articulodescuento',
            name='cantidad_restante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
